imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LpsaUserBundle/Resources/config/services.yml" }
    - { resource: "@LpsaAdminBundle/Resources/config/services.yml" }
    - { resource: "@LpsaCoreBundle/Resources/config/services.yml" }
    - { resource: "@LpsaMailBundle/Resources/config/services.yml" }
    - { resource: "@LpsaChartBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
    globals:
        lpsa_typecorporel_ids: "%typecorporel_ids%"
        lpsa_nb_max_file_upload: "%nb_max_file_upload%"
        lpsa_categories: "%categories_id%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

# fos user
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Lpsa\UserBundle\Entity\User
    group:
        form:
            type: lpsa_admin_user_group
        group_class: Lpsa\UserBundle\Entity\Group
    profile:
        form:
            type: lpsa_admin_user_profile
    registration:
        form:
            type: lpsa_admin_user_registration

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: LpsaAppBundle:Pagination:pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - LpsaAdminBundle
    filters:
        cssrewrite: ~
    assets:
        font-awesome-ttf:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-svg:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-eot:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-otf:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-woff2:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'
        bootstrap-glyphicons-eot:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        bootstrap-glyphicons-svg:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        bootstrap-glyphicons-ttf:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        bootstrap-glyphicons-woff:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        bootstrap-glyphicons-woff2:
            inputs: '@LpsaAdminBundle/Resources/public/vendor/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
