<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * CorporelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporelRepository extends AbstractGenericRepository
{
    /**
     * 
     * @param int $id
     * @return mixed
     */
    public function findAllCorporelByTypeCorporel($id){
        $qb = $this->createQueryBuilder('corpo');
        $qb->select('corpo')
            ->innerJoin('corpo.typeCorporel', 'typeCorporel')
            ->where('typeCorporel.id = :id')
            ->setParameter('id', $id);
        $q = $qb->getQuery();

        return $q->getResult();
    }
}
