<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * DepotCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotCategorieRepository extends AbstractGenericRepository
{    
}
