<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;
/**
 * EnvironnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironnementRepository extends AbstractGenericRepository
{
    /**
     * 
     * @param int $id
     * @return mixed
     */
    public function findAllEnvironnementByTypeEnvironnement($id){
        $qb = $this->createQueryBuilder('env');
        $qb->select('env')
            ->innerJoin('env.typeEnvironnement', 'typeEnvironnement')
            ->where('typeEnvironnement.id = :id')
            ->setParameter('id', $id);
        $q = $qb->getQuery();

        return $q->getResult();
    }
    
    /**
     * 
     * @return mixed
     */
    public function findAllEnvironnementWhereInputIsVisible(){
        $qb = $this->createQueryBuilder('env');
        $qb->select('env')
            ->where('env.afficheNbre = :nb')
            ->setParameter('nb', true);
        $q = $qb->getQuery();

        return $q->getResult();
    }
}
