<?php

namespace Lpsa\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementCategorieTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementCategorieTableRepository extends EntityRepository
{
}
