<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuiteProduitRepository extends AbstractGenericRepository
{
    public function findAllByYear($year){
        $qb = $this->createQueryBuilder('f');
        $qb->select('f')
            ->where('f.annee = :year')
            ->setParameter('year',$year)
        ;
        $qb->orderBy('f.mois','ASC');

        return $qb->getQuery()->getResult();
    }
}
