<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;
/**
 * HeureTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureTravailRepository extends AbstractGenericRepository
{
    public function findAllByYear($year){
        $qb = $this->createQueryBuilder('hour');
        $qb->select(array('hour','heureTravailCategorie'))
            ->join('hour.heureTravailCategorie','heureTravailCategorie')
            ->where('hour.annee = :year')
            ->setParameter('year',$year)
        ;
        $qb->orderBy('hour.mois','ASC');

        return $qb->getQuery()->getResult();
    }
}
