<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * IndicateurTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicateurTransportRepository extends AbstractGenericRepository
{
    public function findAllByYear($year){
        $qb = $this->createQueryBuilder('indicateur');
        $qb->select('indicateur')
            ->where('indicateur.annee = :year')
            ->setParameter('year',$year)
        ;
        $qb->orderBy('indicateur.mois','ASC');

        return $qb->getQuery()->getResult();
    }
}
