<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * MaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielRepository extends AbstractGenericRepository
{
    /**
     * 
     * @param int $id
     * @return mixed
     */
    public function findAllMaterielByTypeMateriel($id){
        $qb = $this->createQueryBuilder('materiel');
        $qb->select('materiel')
            ->innerJoin('materiel.typeMateriel', 'typeMateriel')
            ->where('typeMateriel.id = :id')
            ->setParameter('id', $id);
        $q = $qb->getQuery();

        return $q->getResult();
    }
}
