<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * ObjectifKpihseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifKpihseRepository extends AbstractGenericRepository
{
    public function findByYear($year){
        $qb = $this->createQueryBuilder('o');
        $qb->select('o')
            ->where('o.annee = :year')
            ->setParameter('year',$year)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
