<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * ObjectifDepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifDepotRepository extends AbstractGenericRepository
{
  
    public function fetchAll(){
        $qb = $this->createQueryBuilder('o');
        $qb->select('o,d')
            ->innerJoin('o.depot', 'd');
        return $qb->getQuery();
    }
}
