<?php

namespace Lpsa\AppBundle\Repository;

/**
 * Paq3seRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Paq3seRepository extends \Doctrine\ORM\EntityRepository
{
}
