<?php

namespace Lpsa\AppBundle\Repository;

use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Paq3seGraviteRepository extends AbstractGenericRepository
{
    /**
     * 
     * @param int $id
     * @return mixed
     */
    public function findOneGravity(){
        $qb = $this->createQueryBuilder('g');
        $qb->select(array('g','gravite'))
            ->innerJoin('g.gravite', 'gravite')
            ->setMaxResults(1);
        $q = $qb->getQuery();

        return $q->getOneOrNullResult();
    }
}
