<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends AbstractGenericRepository
{
    /**
     * 
     * @param int $id
     * @return mixed
     */
    public function findAllServicesByDepartement($id){
        $qb = $this->createQueryBuilder('se');
        $qb->select('se')
            ->innerJoin('se.departement', 'departement')
            ->where('departement.id = :id')
            ->setParameter('id', $id);
        $q = $qb->getQuery();

        return $q->getResult();
    }
}
