<?php

namespace Lpsa\AppBundle\Repository;
use Lpsa\CoreBundle\Repository\AbstractGenericRepository;
/**
 * ToolboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolboxRepository extends AbstractGenericRepository
{
    public function findAllByYear($year){
        $qb = $this->createQueryBuilder('tool');
        $qb->select('tool')
            ->where('tool.annee = :year')
            ->setParameter('year',$year)
        ;
        $qb->orderBy('tool.mois','ASC');

        return $qb->getQuery()->getResult();
    }
}
