admin_dysfonctionnement_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:index" }
    methods:  GET

admin_dysfonctionnement_show:
    path:     /{id}/show
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:show" }
    methods:  GET

admin_dysfonctionnement_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:newEdit" }
    methods:  [GET, POST]
    
admin_dysfonctionnement_create:
    path:     /create
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:create" }
    methods:  POST

admin_dysfonctionnement_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:newEdit" }

admin_dysfonctionnement_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:Dysfonctionnement:delete" }
    
