evenementstatut_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:EvenementStatut:index" }
    methods:  GET

evenementstatut_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:EvenementStatut:newEdit" }
    methods:  [GET, POST]

evenementstatut_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:EvenementStatut:newEdit" }
    methods:  [GET, PUT]
    requirements:
       id: \d+

evenementstatut_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:EvenementStatut:delete" }
    requirements:
       id: \d+
