heuretravail_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:HeureTravail:index" }
    methods:  GET

heuretravail_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:HeureTravail:newEdit" }
    methods:  [GET, POST]

heuretravail_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:HeureTravail:newEdit" }
    methods:  [GET, PUT]
    requirements:
       id: \d+

heuretravail_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:HeureTravail:delete" }
    requirements:
       id: \d+
