materiel_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:Materiel:index" }
    methods:  GET

materiel_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:Materiel:newEdit" }
    methods:  GET|PUT
    requirements:
       id: \d+

materiel_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:Materiel:newEdit" }
    methods:  GET|POST

materiel_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:Materiel:delete" }
    requirements:
       id: \d+

