decanteur_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:Decanteur:index" }
    methods:  GET
    options:
        section: [KPIHSE,DECANTEUR]

decanteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:Decanteur:newEdit" }
    methods:  GET|PUT
    requirements:
       id: \d+
    options:
        section: [KPIHSE,DECANTEUR]

decanteur_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:Decanteur:newEdit" }
    methods:  GET|POST
    options:
        section: [KPIHSE,DECANTEUR]

decanteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:Decanteur:delete" }
    requirements:
       id: \d+
    options:
        section: [KPIHSE,DECANTEUR]

