exerciceurgence_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:ExerciceUrgence:index" }
    methods:  GET
    options:
        section: [KPIHSE,EXERCICE_URGENCE]

exerciceurgence_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:ExerciceUrgence:newEdit" }
    methods:  [GET, POST]
    options:
        section: [KPIHSE,EXERCICE_URGENCE]

exerciceurgence_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:ExerciceUrgence:newEdit" }
    methods:  [GET, PUT]
    requirements:
       id: \d+
    options:
        section: [KPIHSE,EXERCICE_URGENCE]

exerciceurgence_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:ExerciceUrgence:delete" }
    requirements:
       id: \d+
    options:
        section: [KPIHSE,EXERCICE_URGENCE]
