objectifKpihse_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:ObjectifKpihse:index" }
    methods:  GET
    options:
        section: [KPIHSE,OBJECTIF_KPI]

objectifKpihse_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:ObjectifKpihse:newEdit" }
    methods:  GET|PUT
    requirements:
       id: \d+
    options:
        section: [KPIHSE,OBJECTIF_KPI]

objectifKpihse_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:ObjectifKpihse:newEdit" }
    methods:  GET|POST
    options:
        section: [KPIHSE,OBJECTIF_KPI]

objectifKpihse_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:ObjectifKpihse:delete" }
    requirements:
       id: \d+
    options:
        section: [KPIHSE,OBJECTIF_KPI]

