piezometre_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:Piezometre:index" }
    methods:  GET
    options:
        section: [KPIHSE,PIEZOMETRE]

piezometre_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:Piezometre:newEdit" }
    methods:  GET|PUT
    requirements:
       id: \d+
    options:
        section: [KPIHSE,PIEZOMETRE]

piezometre_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:Piezometre:newEdit" }
    methods:  GET|POST
    options:
        section: [KPIHSE,PIEZOMETRE]

piezometre_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:Piezometre:delete" }
    requirements:
       id: \d+
    options:
        section: [KPIHSE,PIEZOMETRE]

