visite_index:
    path:     /
    defaults: { _controller: "LpsaAppBundle:Visite:index" }
    methods:  GET
    options:
        section: [KPIHSE,VISITE]

visite_edit:
    path:     /{id}/edit
    defaults: { _controller: "LpsaAppBundle:Visite:newEdit" }
    methods:  GET|PUT
    requirements:
       id: \d+
    options:
        section: [KPIHSE,VISITE]

visite_new:
    path:     /new
    defaults: { _controller: "LpsaAppBundle:Visite:newEdit" }
    methods:  GET|POST
    options:
        section: [KPIHSE,VISITE]

visite_delete:
    path:     /{id}/delete
    defaults: { _controller: "LpsaAppBundle:Visite:delete" }
    requirements:
       id: \d+
    options:
        section: [KPIHSE,VISITE]

